#ifndef SYPHONOUT_CORE_H
#define SYPHONOUT_CORE_H

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Output operating mode — C-repr so cbindgen exports it correctly.
typedef enum SyphonOutMode {
    SYPHON_OUT_MODE_SIGNAL = 0,
    SYPHON_OUT_MODE_FREEZE = 1,
    SYPHON_OUT_MODE_BLANK_BLACK = 2,
    SYPHON_OUT_MODE_BLANK_WHITE = 3,
    SYPHON_OUT_MODE_BLANK_TEST_PATTERN = 4,
    SYPHON_OUT_MODE_OFF = 5,
} SyphonOutMode;

// Global menu-bar icon state.
typedef enum SyphonOutIcon {
    // ● All active outputs have live signal
    SYPHON_OUT_ICON_SOLID = 0,
    // ◑ At least one output frozen / no signal
    SYPHON_OUT_ICON_HALF = 1,
    // ○ All outputs blank or off
    SYPHON_OUT_ICON_EMPTY = 2,
} SyphonOutIcon;

// Per-output signal status.
typedef enum SyphonOutSignal {
    SYPHON_OUT_SIGNAL_PRESENT = 0,
    SYPHON_OUT_SIGNAL_NO_SIGNAL = 1,
    SYPHON_OUT_SIGNAL_NO_SOURCE_SELECTED = 2,
} SyphonOutSignal;

// Server description, passed to Swift callbacks.
// All pointers are valid only for the duration of the callback invocation.
typedef struct SyphonOutServerInfo {
    const char *uuid;
    const char *name;
    const char *app_name;
} SyphonOutServerInfo;

// Initialise the Rust core. Call once from AppDelegate before any other function.
void syphonout_core_init(void);

// Tear down the core (call from applicationWillTerminate).
void syphonout_core_deinit(void);

// Create a Metal-backed output for `display_id`.
// `ca_metal_layer_ptr` is the raw `CAMetalLayer *` created by Swift.
void syphonout_output_create(uint32_t display_id, void *ca_metal_layer_ptr);

// Remove an output (call when a display is disconnected).
void syphonout_output_destroy(uint32_t display_id);

// Transition an output to a new mode.
void syphonout_output_set_mode(uint32_t display_id, enum SyphonOutMode mode);

// Assign a Syphon server to an output. `server_uuid` is a null-terminated UTF-8 string.
void syphonout_output_set_server(uint32_t display_id, const char *server_uuid);

// Remove the server assignment from an output.
void syphonout_output_clear_server(uint32_t display_id);

// Draw the current frame into the output's CAMetalLayer.
// Called from a CVDisplayLink background thread — Metal is thread-safe.
void syphonout_render_frame(uint32_t display_id);

// Set the crossfade duration in milliseconds.
void syphonout_set_crossfade_duration_ms(double ms);

// Set whether mirroring is enabled and which display is the primary source.
void syphonout_set_mirror(bool enabled, uint32_t primary_display_id);

// Register a callback invoked (on an arbitrary thread) when the server list changes.
// Swift should dispatch to main thread and rebuild the menu.
void syphonout_set_server_changed_callback(void (*callback)(void*), void *userdata);

// Enumerate all currently available Syphon servers.
// `callback` is invoked synchronously with an array of SyphonOutServerInfo.
void syphonout_get_servers(void (*callback)(const struct SyphonOutServerInfo*, uintptr_t, void*),
                           void *userdata);

// Get the overall icon state for the menu bar.
enum SyphonOutIcon syphonout_get_icon_state(void);

// Get the signal status for a specific display.
enum SyphonOutSignal syphonout_get_signal_status(uint32_t display_id);

// Returns a pointer to a null-terminated server name string, or NULL.
// The pointer is valid until the next call to this function for the same display_id.
const char *syphonout_get_selected_server_name(uint32_t display_id);

// Server appeared on the network.
void syphonout_on_server_announced(const char *uuid, const char *name, const char *app_name);

// Server left the network.
void syphonout_on_server_retired(const char *uuid);

// New frame available from a Syphon server for a specific output.
// `iosurface_ref` is an `IOSurfaceRef` — the MTLTexture is created zero-copy in Rust.
void syphonout_on_new_frame(uint32_t display_id,
                            void *iosurface_ref,
                            uint32_t width,
                            uint32_t height);

#endif  /* SYPHONOUT_CORE_H */
